---
title: "Seurat 10x tutorial"
author: "Kyle Ireton"
date: "1/11/2022"
output: html_document
---


```{r}

library(dplyr)
library(Seurat)
library(patchwork)

```


```{r}

# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "C:/Users/kylei/OneDrive/Zephyrus/_bioinformatics/Seurat/pbmc3k_filtered_gene_bc_matrices/filtered_gene_bc_matrices/hg19/")

# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data,
                           project = "pbmc3k",
                           min.cells = 3,
                           min.features = 200)

pbmc

```

```{r}

# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

```

```{r, fig.width=10}

# Visualize QC metrics as a violin plot
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

```

```{r, fig.width=10}

# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

```

```{r}

pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

```

```{r}

pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)

```

```{r, fig.width= 10}

pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2

```

```{r}

all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

```

```{r}
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
```


```{r}
# Examine and visualize PCA results a few different ways
print(pbmc[["pca"]], dims = 1:5, nfeatures = 5)

```

```{r}

VizDimLoadings(pbmc, dims = 1:2, reduction = "pca")

```

```{r}

DimPlot(pbmc, reduction = "pca")

```

```{r}

DimHeatmap(pbmc, dims = 1, cells = 500, balanced = TRUE)

```

```{r, fig.height= 12}

DimHeatmap(pbmc, dims = 1:15, cells = 500, balanced = TRUE)

```

```{r}

# NOTE: This process can take a long time for big datasets, comment out for expediency. More
# approximate techniques such as those implemented in ElbowPlot() can be used to reduce
# computation time
pbmc <- JackStraw(pbmc, num.replicate = 100)
pbmc <- ScoreJackStraw(pbmc, dims = 1:20)

```

```{r, fig.width=10, fig.height=8}

JackStrawPlot(pbmc, dims = 1:15)

```

```{r}

ElbowPlot(pbmc)

```

```{r}

pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)

```

```{r}

# Look at cluster IDs of the first 5 cells
head(Idents(pbmc), 5)

```

```{r}

# If you haven't installed UMAP, you can do so via reticulate::py_install(packages =
# 'umap-learn')
pbmc <- RunUMAP(pbmc, dims = 1:10)

```

```{r, fig.width= 8}

# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(pbmc, reduction = "umap")

```

```{r}

saveRDS(pbmc, file = "C:/Users/kylei/OneDrive/Zephyrus/_bioinformatics/Seurat/pbmc_tutorial.rds")

```

```{r}



```

